import "pkg:/source/api/ApiClient.bs"
import "pkg:/source/api/baserequest.bs"
import "pkg:/source/api/sdk.bs"
import "pkg:/source/utils/config.bs"

sub init()
  m.top.functionName = "setFavoriteStatus"
end sub

sub setFavoriteStatus()

  task = m.top.favTask

  if task = "Favorite"
    GetApi().MarkFavorite(m.global.user.id, m.top.itemId)
  else if task = "Unfavorite"
    GetApi().UnmarkFavorite(m.global.user.id, m.top.itemId)
  end if

end sub
