import "pkg:/source/utils/misc.bs"
sub init()
  m.top.content = getData()
end sub

function getData()
  if not isValid(m.top.MusicArtistAlbumData)
    data = CreateObject("roSGNode", "ContentNode")
    return data
  end if

  albumData = m.top.MusicArtistAlbumData
  data = CreateObject("roSGNode", "ContentNode")

  for each song in albumData.items
    data.appendChild(song)
  end for

  m.top.content = data

  m.top.isDoneLoading = true

  return data
end function
