import "pkg:/source/api/ApiClient.bs"
import "pkg:/source/utils/config.bs"

sub init()
  m.top.functionName = "PlaystateUpdate"
end sub

sub PlaystateUpdate()
  params = PlaystateDefaults(m.top.params)

  if m.top.status = "start"
    GetApi().Playing(params)
  else if m.top.status = "stop" or m.top.status = "finished"
    GetApi().PostStopped(params)
  else if m.top.status = "update"
    GetApi().PostProgress(params)
  else
    ' Unknown State
    return
  end if
end sub

function PlaystateDefaults(params = {} as object)
  new_params = {
    '"CanSeek": false
    '"Item": "{}", ' TODO!
    '"NowPlayingQueue": "[]", ' TODO!
    '"PlaylistItemId": "",
    '"ItemId": id,
    '"SessionId": "", ' TODO!
    '"MediaSourceId": id,
    '"AudioStreamIndex": 1,
    '"SubtitleStreamIndex": 0,
    "IsPaused": false,
    '"IsMuted": false,
    "PositionTicks": 0
    '"PlaybackStartTimeTicks": 0,
    '"VolumeLevel": 100,
    '"Brightness": 100,
    '"AspectRatio": "16x9",
    '"PlayMethod": "DirectStream"
    '"LiveStreamId": "",
    '"PlaySessionId": "",
    '"RepeatMode": "RepeatNone"
  }

  paramsArray = params.items()
  for i = 0 to paramsArray.count() - 1
    item = paramsArray[i]
    new_params[item.key] = item.value
  end for
  return new_params
end function
