import "pkg:/source/api/ApiClient.bs"
import "pkg:/source/api/apiPool.bs"
import "pkg:/source/api/baseRequest.bs"
import "pkg:/source/api/image.bs"
import "pkg:/source/api/items.bs"
import "pkg:/source/translationKeys.bs"
import "pkg:/source/utils/config.bs"
import "pkg:/source/utils/deviceCapabilities.bs"
import "pkg:/source/utils/translate.bs"

sub init()
  m.top.layoutDirection = "vert"
  m.top.horizAlignment = "center"
  m.top.vertAlignment = "top"
  m.top.visible = false
  m.searchText = m.top.findNode("searchKey")
  m.searchText.textEditBox.hintText = translate(translationKeys.ButtonSearch)
  m.searchText.keyGrid.keyDefinitionUri = "pkg:/components/data/CustomAddressKDF.json"
  m.searchText.textEditBox.voiceEnabled = true
  m.searchText.textEditBox.active = true
  m.searchText.ObserveField("text", "searchMedias")
  m.searchSelect = m.top.findNode("searchSelect")

  'set lable text
  m.label = m.top.findNode("text")
  m.label.text = translate(translationKeys.LabelSearchNow)

end sub

sub searchMedias()
  m.top.searchValues = m.searchText.text
  if m.top.searchValues.len() > 1
    m.searchText.textEditBox.leadingEllipsis = true
  else
    m.searchText.textEditBox.leadingEllipsis = false
  end if
end sub
