import "pkg:/source/utils/translate.bs"
import "pkg:/source/translationKeys.bs"
sub init()
  m.content = m.top.findNode("content")
  m.top.observeField("contentData", "onContentDataChanged")

  m.top.id = "OKDialog"
  m.top.height = 900
  m.top.buttons = [translate(translationKeys.ButtonOk)]

  constants = m.global.constants

  m.dialogStyles = {
    "default": {
      "fontSize": 27,
      "fontUri": "font:BoldSystemFontFile",
      "color": constants.colorTextPrimary
    },
    "b": {
      "fontSize": 27,
      "fontUri": "font:SystemFontFile",
      "color": constants.colorTextSecondary
    },
    "header": {
      "fontSize": 35,
      "fontUri": "font:SystemFontFile",
      "color": constants.colorSecondary
    },
    "p": {
      "fontSize": 27,
      "fontUri": "font:SystemFontFile",
      "color": constants.colorTextPrimary
    }
  }

end sub

sub onContentDataChanged()
  for each item in m.top.contentData.data
    textLine = m.content.CreateChild("StdDlgMultiStyleTextItem")
    textLine.drawingStyles = m.dialogStyles
    textLine.text = item
  end for
end sub
