/**
 * scripts/screenshots-index.js — generate docs/screenshots/README.md, a
 * by-language index that GitHub renders when you open the folder. It lists the
 * store languages (with `home` thumbnails) and, once more locales are captured,
 * every captured language as a native-name link. Native names come from
 * locale/languages.json; the curated store set from RTA_CONFIG.storeLanguages.
 *
 * Regenerated alongside the screenshots (called by scripts/capture-screenshots.js)
 * and runnable standalone: `npm run screenshots:index`. The output is generated —
 * DO NOT hand-edit it; change this generator or tests/rta/config.js.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { RTA_CONFIG } from '../tests/rta/config.js';

const repoRoot = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const shotsDir = path.join(repoRoot, 'docs', 'screenshots');
const languagesJson = path.join(repoRoot, 'locale', 'languages.json');

export function generateIndex() {
  const nativeByCode = Object.fromEntries(
    JSON.parse(fs.readFileSync(languagesJson, 'utf8')).map((l) => [l.code, l.nativeName]),
  );
  const nativeName = (code) => nativeByCode[code] || code;

  // Captured locales = subfolders that actually contain a screenshot.
  const captured = fs
    .readdirSync(shotsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .filter((name) => fs.readdirSync(path.join(shotsDir, name)).some((f) => f.endsWith('.png')));

  const storeCaptured = RTA_CONFIG.storeLanguages.filter((c) => captured.includes(c));
  const hasNonStore = captured.some((c) => !RTA_CONFIG.storeLanguages.includes(c));
  const byNative = (a, b) => nativeName(a).localeCompare(nativeName(b));

  const thumb = (code) => {
    const files = fs.readdirSync(path.join(shotsDir, code));
    const home = files.includes('home.png') ? 'home.png' : files.find((f) => f.endsWith('.png'));
    return `<a href="${code}/" title="${nativeName(code)}"><img src="${code}/${home}" width="190" alt="${nativeName(code)}"></a>`;
  };
  const link = (code) => `[${nativeName(code)}](${code}/)`;

  let md = '<!-- markdownlint-disable -->\n';
  md += '<!--\n';
  md += '  THIS FILE IS AUTO-GENERATED by scripts/screenshots-index.js. DO NOT EDIT BY HAND.\n';
  md += '  Regenerated by `npm run screenshots:index` and every `npm run screenshots:capture`.\n';
  md +=
    '  To change which languages appear, edit tests/rta/config.js (languages / storeLanguages).\n';
  md += '-->\n\n';
  md += '# JellyRock screenshots by language\n\n';
  md +=
    '> 🤖 Auto-generated — do not edit by hand. Pick a language to view its screenshot set ' +
    '(User Select, Home, Library Grid, Movie Details, OSD, Trickplay).\n\n';
  md += '## Store languages\n\n';
  md += `<p align="center">\n${storeCaptured.map(thumb).join('\n')}\n</p>\n\n`;
  md += storeCaptured.map(link).join(' · ') + '\n';
  if (hasNonStore) {
    md += '\n## All captured languages\n\n';
    md += [...captured].sort(byNative).map(link).join(' · ') + '\n';
  }

  const dest = path.join(shotsDir, 'README.md');
  fs.writeFileSync(dest, md);
  return { dest, captured: captured.length, store: storeCaptured.length };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const r = generateIndex();
  console.log(
    `wrote ${path.relative(repoRoot, r.dest)} (${r.store} store, ${r.captured} captured languages)`,
  );
}
