name: lint-translation-files

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone github repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Lint translation files
        run: npm run lint:translations
      - name: Validate translation key usage
        run: npm run validate:translations
      - name: Lint XML translation attributes
        run: npm run lint:xml-translations
