name: "Close stale Pull Requests"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    if: github.repository == 'jellyrock/jellyrock'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/stale@1e223db275d687790206a7acac4d1a11bd6fe629 # v10.4.0
        with:
          days-before-issue-stale: -1
          days-before-issue-close: -1
          stale-pr-label: stale
          stale-pr-message: "This pull request has been inactive for 30 days and will be automatically closed in 15 days if there is no further activity."
          close-pr-message: "This pull request has been closed because it has been inactive for 45 days. You may submit a new pull request if desired."
          days-before-pr-stale: 30
          days-before-pr-close: 15
          exempt-draft-pr: true
          repo-token: ${{ steps.app-token.outputs.token }}
