name: lint-translation-files
on:
  pull_request:
    paths:
      - "locale/custom/*.json"
      - "source/**/*.bs"
      - "components/**/*.bs"
      - "settings/settings.json"
      - "scripts/lint-translations.cjs"
      - "scripts/validate-translations.cjs"

jobs:
  run:
    uses: ./.github/workflows/_lint-translation-files.yml
